const equipmentCards = [
  {
    equipmentName: "Monster's Bane",
    rank: "1",
    slot: "weapon",
    set: "Slayer",
    element: "none",
    bonus: "monsters",
  },
  {
    equipmentName: "Duelist's Edge",
    rank: "1",
    slot: "weapon",
    set: "Duelist",
    element: "none",
    bonus: "players",
  },
  {
    equipmentName: "Doom Blade",
    rank: "1",
    slot: "weapon",
    set: "Conquerer",
    element: "none",
    bonus: "titans",
  },
  {
    equipmentName: "Guardian's Defender",
    rank: "1",
    slot: "weapon",
    set: "Guardian",
    element: "none",
    bonus: "defending",
  },
  {
    equipmentName: "Striker's Fury",
    rank: "1",
    slot: "weapon",
    set: "Berserker",
    element: "none",
    bonus: "attacking",
  },
  {
    equipmentName: "Beastguard Plate",
    rank: "1",
    slot: "armor",
    set: "Slayer",
    element: "none",
    bonus: "monsters",
  },
  {
    equipmentName: "Rival's Ward",
    rank: "1",
    slot: "armor",
    set: "Duelist",
    element: "none",
    bonus: "players",
  },
  {
    equipmentName: "Fortress Mail",
    rank: "1",
    slot: "armor",
    set: "Conquerer",
    element: "none",
    bonus: "titans",
  },
  {
    equipmentName: "Bastion Plate",
    rank: "1",
    slot: "armor",
    set: "Guardian",
    element: "none",
    bonus: "defending",
  },
  {
    equipmentName: "Onslaught Mail",
    rank: "1",
    slot: "armor",
    set: "Berserker",
    element: "none",
    bonus: "attacking",
  },
  {
    equipmentName: "Beastmaster Talisman",
    rank: "1",
    slot: "amulet",
    set: "Slayer",
    element: "none",
    bonus: "monsters",
  },
  {
    equipmentName: "Challenger's Heart",
    rank: "1",
    slot: "amulet",
    set: "Duelist",
    element: "none",
    bonus: "players",
  },
  {
    equipmentName: "Sentinel's Locket",
    rank: "1",
    slot: "amulet",
    set: "Conquerer",
    element: "none",
    bonus: "titans",
  },
  {
    equipmentName: "Bulwark Charm",
    rank: "1",
    slot: "amulet",
    set: "Guardian",
    element: "none",
    bonus: "defending",
  },
  {
    equipmentName: "Aggressor's Totem",
    rank: "1",
    slot: "amulet",
    set: "Berserker",
    element: "none",
    bonus: "attacking",
  },
  {
    equipmentName: "Tracker's Stride",
    rank: "1",
    slot: "boots",
    set: "Slayer",
    element: "none",
    bonus: "monsters",
  },
  {
    equipmentName: "Competitor's Pace",
    rank: "1",
    slot: "boots",
    set: "Duelist",
    element: "none",
    bonus: "players",
  },
  {
    equipmentName: "Swiftstand Boots",
    rank: "1",
    slot: "boots",
    set: "Conquerer",
    element: "none",
    bonus: "titans",
  },
  {
    equipmentName: "Groundhold Greaves",
    rank: "1",
    slot: "boots",
    set: "Guardian",
    element: "none",
    bonus: "defending",
  },
  {
    equipmentName: "Charge Boots",
    rank: "1",
    slot: "boots",
    set: "Berserker",
    element: "none",
    bonus: "attacking",
  },
  {
    equipmentName: "Grasp of the Wild",
    rank: "1",
    slot: "gloves",
    set: "Slayer",
    element: "none",
    bonus: "monsters",
  },
  {
    equipmentName: "Duelist's Touch",
    rank: "1",
    slot: "gloves",
    set: "Duelist",
    element: "none",
    bonus: "players",
  },
  {
    equipmentName: "Rampart Hands",
    rank: "1",
    slot: "gloves",
    set: "Conquerer",
    element: "none",
    bonus: "titans",
  },
  {
    equipmentName: "Mason's Safegaurd",
    rank: "1",
    slot: "gloves",
    set: "Guardian",
    element: "none",
    bonus: "defending",
  },
  {
    equipmentName: "Siege Hands",
    rank: "1",
    slot: "gloves",
    set: "Berserker",
    element: "none",
    bonus: "attacking",
  },
];

module.exports = equipmentCards;